basecalled_dir: "/ssd_workspace/jpeter/ssData/Guppy_basecalling/20230131_1436_MN26523_FAS60584_9ae1905f/workspace"
outdir: "/home/jpeter/DATA/NanoRACE/Test_RACE/OUTDIR2"
barcode_corr: "/home/jpeter/DATA/FLEPseq/RUN08_Fleurs_v4/barcode_correspondances.tsv"


runs_dir: "1_Runs"
mapping_dir: "2_Mapping"
polyA_dir: "3_PolyA"
tail_dir: "4_Tail"

introns_exons: "/home/jpeter/DATA/NanoRACE/Test_RACE/NanoRACE_RUN03_31012023_exon_intron_posV2.bed"
select_introns: "/home/jpeter/DATA/ReferenceGenomes/Athaliana/TAIR10/select_introns.txt"

reference_genome: "/home/jpeter/DATA/NanoRACE/Test_RACE/NanoRACE_RUN03_31012023_mapping.fa" # Reference genome in fasta

## MINIMAP MAPPING ADDITIONAL PARAMETERS
minimap2_add_opts: "--secondary=no -G 5000"